const province = [
    { id: 0, label: "TP Hồ Chí Minh", data_label: "b'TP. H\xe1\xbb\x93 Ch\xc3\xad Minh'" },
    { id: 1, label: "Bình dương", data_label: "b'B\xc3\xacnh D\xc6\xb0\xc6\xa1ng'" },
    { id: 2, label: "Đồng Nai", data_label: "b'\xc4\x90\xe1\xbb\x93ng Nai'" },
    { id: 3, label: "Long An", data_label: "b'Long An'" },
    { id: 4, label: "Tiền Giang", data_label: "b'Ti\xe1\xbb\x81n Giang'" },
    { id: 5, label: "An Giang", data_label: "b'An Giang'" },
    { id: 6, label: "Tây Ninh", data_label: "b'T\xc3\xa2y Ninh'" },
    { id: 7, label: "Kiên Giang", data_label: "b'Ki\xc3\xaan Giang'" },
    { id: 8, label: "Đồng Tháp", data_label: "b'\xc4\x90\xe1\xbb\x93ng Th\xc3\xa1p'" },
    { id: 9, label: "Khánh Hoà", data_label: "b'Kh\xc3\xa1nh H\xc3\xb2a'" },
    { id: 10, label: "Bình Thuận", data_label: "b'B\xc3\xacnh Thu\xe1\xba\xadn'" },
    { id: 11, label: "Cần Thơ", data_label: "b'C\xe1\xba\xa7n Th\xc6\xa1'" },
    { id: 12, label: "Sóc Trăng", data_label: "b'S\xc3\xb3c Tr\xc4\x83ng'" },
    { id: 13, label: "Bạc Liêu", data_label: "b'B\xe1\xba\xa1c Li\xc3\xaau'" },
    { id: 14, label: "Bà Rịa - Vũng Tàu", data_label: "b'B\xc3\xa0 R\xe1\xbb\x8ba - V\xc5\xa9ng T\xc3\xa0u'" },
    { id: 15, label: "Hà Nội", data_label: "b'H\xc3\xa0 N\xe1\xbb\x99i'" },
    { id: 16, label: "Bắc Giang", data_label: "b'B\xe1\xba\xafc Giang'" },
    { id: 17, label: "Đăk lắk", data_label: "b'\xc4\x90\xe1\xba\xafk L\xe1\xba\xafk'" },
    { id: 18, label: "Đà Nẵng", data_label: "b'\xc4\x90\xc3\xa0 N\xe1\xba\xb5ng'" },
    { id: 19, label: "Vĩnh Long", data_label: "b'V\xc4\xa9nh Long'" },
    { id: 20, label: "Cà Mau", data_label: "b'C\xc3\xa0 Mau'" },
    { id: 21, label: "Trà Vinh", data_label: "b'Tr\xc3\xa0 Vinh'" },
    { id: 22, label: "Bến Tre", data_label: "b'B\xe1\xba\xbfn Tre'" },
    { id: 23, label: "Bình Phước", data_label: "b'B\xc3\xacnh Ph\xc6\xb0\xe1\xbb\x9bc'" },
    { id: 24, label: "Phú Yên", data_label: "b'Ph\xc3\xba Y\xc3\xaan'" },
    { id: 25, label: "Nghệ An", data_label: "b'Ngh\xe1\xbb\x87 An'" },
    { id: 26, label: "Ninh Thuận", data_label: "b'Ninh Thu\xe1\xba\xadn'" },
    { id: 27, label: "Bắc Ninh", data_label: "b'B\xe1\xba\xafc Ninh'" },
    { id: 28, label: "Hà Giang", data_label: "b'H\xc3\xa0 Giang'" },
    { id: 29, label: "Bình Định", data_label: "b'B\xc3\xacnh \xc4\x90\xe1\xbb\x8bnh'" },
    { id: 30, label: "Gia Lai", data_label: "b'Gia Lai'" },
    { id: 31, label: "Hậu Giang", data_label: "b'H\xe1\xba\xadu Giang'" },
    { id: 32, label: "Quảng Bình", data_label: "b'Qu\xe1\xba\xa3ng B\xc3\xacnh'" },
    { id: 33, label: "Quảng Ngãi", data_label: "b'Qu\xe1\xba\xa3ng Ng\xc3\xa3i'" },
    { id: 34, label: "Quảng Nam", data_label: "b'Qu\xe1\xba\xa3ng Nam'" },
    { id: 35, label: "Thừa Thiên - Huế", data_label: "b'Th\xe1\xbb\xaba Thi\xc3\xaan \xe2\x80\x93 Hu\xe1\xba\xbf'" },
    { id: 36, label: "Thanh Hoá", data_label: "b'Thanh H\xc3\xb3a'" },
    { id: 37, label: "Đăk Nông", data_label: "b'\xc4\x90\xe1\xba\xafk N\xc3\xb4ng'" },
    { id: 38, label: "Phú Thọ", data_label: "b'Ph\xc3\xba Th\xe1\xbb\x8d'" },
    { id: 39, label: "Hải Dương", data_label: "b'H\xe1\xba\xa3i D\xc6\xb0\xc6\xa1ng'" },
    { id: 40, label: "Hà Nam", data_label: "b'H\xc3\xa0 Nam'" },
    { id: 41, label: "Lâm Đồng", data_label: "b'L\xc3\xa2m \xc4\x90\xe1\xbb\x93ng'" },
    { id: 42, label: "Nam Định", data_label: "b'Nam \xc4\x90\xe1\xbb\x8bnh'" },
    { id: 43, label: "Hà Tĩnh", data_label: "b'H\xc3\xa0 T\xc4\xa9nh'" },
    { id: 44, label: "Thái Bình", data_label: "b'Th\xc3\xa1i B\xc3\xacnh'" },
    { id: 45, label: "Quảng Trị", data_label: "b'Qu\xe1\xba\xa3ng Tr\xe1\xbb\x8b'" },
    { id: 46, label: "Hưng Yên", data_label: "b'H\xc6\xb0ng Y\xc3\xaan'" },
    { id: 47, label: "Quảng Ninh", data_label: "b'Qu\xe1\xba\xa3ng Ninh'" },
    { id: 48, label: "Vĩnh Phúc", data_label: "b'V\xc4\xa9nh Ph\xc3\xbac'" },
    { id: 49, label: "Kon Tum", data_label: "b'Kon Tum'" },
    { id: 50, label: "Sơn La", data_label: "b'S\xc6\xa1n La'" },
    { id: 51, label: "Lạng Sơn", data_label: "b'L\xe1\xba\xa1ng S\xc6\xa1n'" },
    { id: 52, label: "Ninh Bình", data_label: "b'Ninh B\xc3\xacnh'" },
    { id: 53, label: "Điện Biên", data_label: "b'\xc4\x90i\xe1\xbb\x87n Bi\xc3\xaan'" },
    { id: 54, label: "Hải Phòng", data_label: "b'H\xe1\xba\xa3i Ph\xc3\xb2ng'" },
    { id: 55, label: "Tuyên Quang", data_label: "b'Tuy\xc3\xaan Quang'" },
    { id: 56, label: "Lào Cai", data_label: "b'L\xc3\xa0o Cai'" },
    { id: 57, label: "Thái Nguyên", data_label: "b'Th\xc3\xa1i Nguy\xc3\xaan'" },
    { id: 58, label: "Hoà Bình", data_label: "b'H\xc3\xb2a B\xc3\xacnh'	" },
    { id: 59, label: "Lai Châu", data_label: "b'Lai Ch\xc3\xa2u'" },
    { id: 60, label: "Cao Bằng", data_label: "b'Cao B\xe1\xba\xb1ng'" },
    { id: 61, label: "Yên Bái", data_label: "b'Y\xc3\xaan B\xc3\xa1i'" },
    { id: 62, label: "Bắc Kạn", data_label: "b'B\xe1\xba\xafc K\xe1\xba\xa1n'" },
    { id: 63, label: "Tất cả", data_label: "b'63/63 '" },
]